import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Setup & Paths
CSV_ROOT = "../../yolo/3_fold_cross_validation_csvs"
OUTPUT_PLOTS_DIR = "fold_cross_val_plots"
SAVE_PLOTS = False

if SAVE_PLOTS:
    os.makedirs(OUTPUT_PLOTS_DIR, exist_ok=True)

# Common curves generated by YOLO
CURVE_NAMES = ["Precision_ConfidenceB", "Recall_ConfidenceB", "Precision_RecallB", "F1_ConfidenceB"]
SPLITS = ["validation", "test"]

def aggregate_and_plot(curve_name, split_type):
    all_folds_data = []
    
    # Collect data from each fold
    for i in range(1, 4):
        fold_label = f"fold_{i}"
        csv_path = os.path.join(CSV_ROOT, fold_label, split_type, f"{curve_name}.csv")
        
        if os.path.exists(csv_path):
            df = pd.read_csv(csv_path)
            all_folds_data.append(df)
    
    if not all_folds_data:
        return

    # Standardize X-axis to a common grid
    common_x = np.linspace(0, 1, 100)
    y_interp_list = []
    fold_aucs = []

    plt.figure(figsize=(8, 6))

    for idx, df in enumerate(all_folds_data):
        # calculate fold aucs
        x_col, y_col = df.columns[0], df.columns[1]
        
        # Interpolate fold data to the common X grid
        y_interp = np.interp(common_x, df[x_col], df[y_col])
        y_interp_list.append(y_interp)

        fold_auc = np.trapz(y_interp, common_x)
        fold_aucs.append(fold_auc)
        
        # Plot individual fold
        plt.plot(common_x, y_interp, alpha=0.5, linewidth=2,label=f"Fold {idx+1} (AUC: {fold_auc:.3f})")

    # Calculate Mean and Std
    y_mean = np.mean(y_interp_list, axis=0)
    y_std = np.std(y_interp_list, axis=0)

    # --- Calculate mean AUC of curves ---
    # NOTE: Technically, only relevant for precision-recall :)
    mean_auc = np.trapz(y_mean, common_x)
    std_auc = np.std(fold_aucs)

    if "F1" in curve_name:
        peak_idx = np.argmax(y_mean)
        peak_f1 = y_mean[peak_idx]
        peak_conf = common_x[peak_idx]
        
        plt.scatter(peak_conf, peak_f1, color='black', s=50, zorder=5, label=f'Peak F1: {peak_f1:.2f}')
        plt.annotate(f"Peak F1: {peak_f1:.2f} @ {peak_conf:.2f}", 
                     xy=(peak_conf, peak_f1), 
                     xytext=(peak_conf, peak_f1 + 0.05),
                     ha='center', weight='bold', color='black')
        print(f"[{split_type}] Peak F1: {peak_f1:.4f} at Confidence: {peak_conf:.4f}")

    # Plot Mean Line
    plt.plot(common_x, y_mean, color='blue', linewidth=2, label=f'Mean Curve (AUC: {mean_auc:.3f})')
    plt.fill_between(common_x, y_mean - y_std, y_mean + y_std, color='blue', alpha=0.1, label='±1 SD')

    plt.title(f"Aggregated {curve_name} - {split_type.capitalize()}\nMean AUC: {mean_auc:.4f} ± {std_auc:.4f}")
    plt.xticks(fontsize=14)
    plt.yticks(fontsize=14)
    plt.xlabel(all_folds_data[0].columns[0], fontsize=14)
    plt.ylabel(all_folds_data[0].columns[1], fontsize=14)
    plt.legend(loc='lower left', fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.ylim([0, 1.05])
    plt.xlim([0, 1.0])

    plot_filename = os.path.join(OUTPUT_PLOTS_DIR, f"mean_{curve_name}_{split_type}.png")
    if SAVE_PLOTS:
        plt.savefig(plot_filename, dpi=300)
    
    print(f"[{split_type.upper()}] {curve_name:25} | Mean AUC: {mean_auc:.4f} | Std: {std_auc:.4f}")

# ------------------------------
print("Starting aggregation and AUC calculation...")

for split in SPLITS:
    print(f"\nResults for {split}:")
    print("-" * 60)
    for curve in CURVE_NAMES:
        aggregate_and_plot(curve, split)

plt.show()
